### ISSUE TITLE
Start on start-up only works after visiting Dashboard

### ISSUE THREAD

**Issue by omgitsraven** [easyphp/DEVSERVER#189] opened 2019-09-12 02:21 UTC
1) I have "Start HTTP server on startup" checked.
2) I have a shortcut to `run-devserver.exe` in my `shell:startup` folder.
3) When I start windows, the EasyPHP icon appears in my tray.
4) Even if I've waited ten minutes after starting windows, visiting both `localhost` and `127.0.0.1` gives me my browser's "unable to connect" message.
5) If I right-click the tray icon and click 'Open Dashboard', within a few seconds the dashboard appears.
6) The button on the dashboard below 'HTTP Server' says "stop", suggesting that it's already running.
7) At this point, *without having touched anything on the dashboard*, if I try `localhost` or `127.0.0.1` again, *they now work*.

**Comment by omgitsraven** [comment] 2019-09-16 01:30
To clarify, this doesn't have anything to do with starting it with Windows; I get the same behaviour if I start it manually later. (Localhost returns nothing until I've opened the dashboard once.)

**Comment by omgitsraven** [comment] 2019-09-16 01:36
Discovered something interesting: if I visit `http://127.0.0.1:1111/` manually in my browser, rather than by right-clicking the tray icon and clicking "open dashboard", then the dashboard appears just fine, BUT, the button below 'HTTP Server' says START, not STOP! So it isn't *visiting* the dashboard page that triggers the port-80 server to finally start—it's something that happens specifically when selecting 'Open Dashboard' from the tray icon's menu. (I've also tried opening the right-click menu but NOT selecting 'open dashboard', and that's definitely not enough—you have to click 'open dashboard' for it to start.)

**Comment by Scott-G** [comment] 2020-01-22 23:56
This has been like this since 17 was first released and is VERY annoying. I have never managed to find a solution or get a response from the developer. After every restart I have to go to the system tray icon and select 'Show Dashboard' to get the servers to start. It's a shame, but I doubt it will be fixed now as development seems to have all but stopped.

**Comment by cyril-fsm** [comment] 2020-10-16 15:52
I found a (dirty) workaround by launching easyphp with a batch in the same folder as "run-devserver.exe".
inside the "run_easyphp.bat" batch:

	set "curpath=%~dp0"
	start run-devserver.exe

	ping 0.0.0.0 -n 1 > NUL
	START "" %curpath%\eds-dashboard\eds-app-launch.exe %curpath%eds-dashboard\eds-dashboard.exe -f %curpath%eds-dashboard\servers_boot.php
	echo waiting...
	ping 0.0.0.0 -n 10 > NUL

(ping loop is just for sleep time)
and make a php script in the eds-dashboard folder "./eds-dashboard/servers_boot.php".
inside the "servers_boot.php" script :
<?php
	// Http Server
	chdir(__DIR__);
	include('conf_httpserver.php');	
	include('../eds-binaries/httpserver/' . $conf_httpserver['httpserver_folder'] . '/eds-app-start.php');

	// Db Server
	include('conf_dbserver.php');	
	include('../eds-binaries/dbserver/' . $conf_dbserver['dbserver_folder'] . '/eds-app-start.php');
?>

**Comment by cyril-fsm** [comment] 2020-10-16 15:53
I found a (dirty) workaround by launching easyphp with a batch in the same folder as "run-devserver.exe".
inside the "run_easyphp.bat" batch:

	set "curpath=%~dp0"
	start run-devserver.exe

	ping 0.0.0.0 -n 1 > NUL
	START "" %curpath%\eds-dashboard\eds-app-launch.exe %curpath%eds-dashboard\eds-dashboard.exe -f %curpath%eds-dashboard\servers_boot.php
	echo waiting...
	ping 0.0.0.0 -n 10 > NUL

(ping loop is just for sleep time)
and make a php script in the eds-dashboard folder "./eds-dashboard/servers_boot.php".
inside the "servers_boot.php" script :

	// Http Server
	chdir(__DIR__);
	include('conf_httpserver.php');	
	include('../eds-binaries/httpserver/' . $conf_httpserver['httpserver_folder'] . '/eds-app-start.php');

	// Db Server
	include('conf_dbserver.php');	
	include('../eds-binaries/dbserver/' . $conf_dbserver['dbserver_folder'] . '/eds-app-start.php');

**Comment by omgitsraven** [comment] 2020-10-16 16:02
I just noticed something -- why is this thread tagged with "enhancement" and "feature request"? This is a bug, it's something that's malfunctioning, it's not something new that we're hoping could be invented, it's functionality that *stopped* working in a recent version even though it used to work.

**Closed** 2021-08-12 08:47 UTC
Labels: enhancement, in progress, feature request

**Comment by spem** [comment] 2022-05-15 19:30
Automatic start of servers not working. DEVSERVER 17

**I tried eds.ini**
> [eds]
Version=17.0
Serie=17
Lang=en
Autostart_httpserver=1
Autostart_dbserver=1
Action: run; FileName: "eds-dashboard/eds-dashboard.exe"; WorkingDir: "eds-dashboard"; Parameters: " servers_start.php allservers"; ShowCmd: hidden; Flags: waituntilterminated;

**I tried run-devserver.ini**
>[StartupAction]
Action: run; FileName: "eds-dashboard/eds-app-stop.exe"; WorkingDir: "eds-dashboard"; Parameters: " eds-dashboard"; ShowCmd: hidden; Flags: waituntilterminated;
Action: run; FileName: "eds-dashboard/eds-dashboard.exe"; WorkingDir: "eds-dashboard"; Parameters: " servers_start.php allservers"; ShowCmd: hidden; Flags: waituntilterminated;
Action: run; FileName: "eds-dashboard/eds-dashboard.exe"; WorkingDir: "eds-dashboard"; Parameters: " -S 127.0.0.1:1111 -c eds-dashboard.ini"; ShowCmd: hidden

**Comment by Scott-G** [comment] 2022-05-26 18:41
I wouldn't hold your breath on this being sorted. It has been an issue since day one of DEVSERVER 17 and it is constantly ignored or the issue is closed without comment.

Such a shame, as it is great system but this makes it pretty much unusable for long term development.😞

**Comment by webitman** [comment] 2022-12-23 23:18
Edit run-devserver.ini
Just add the third Action line to start the server  automatic when starting with windows
[StartupAction]
Action: run; FileName: "eds-dashboard/eds-app-stop.exe"; WorkingDir: "eds-dashboard"; Parameters: " eds-dashboard"; ShowCmd: hidden; Flags: waituntilterminated;
Action: run; FileName: "eds-dashboard/eds-dashboard.exe"; WorkingDir: "eds-dashboard"; Parameters: " -S 127.0.0.1:1111 -c eds-dashboard.ini"; ShowCmd: hidden
**Action: run; FileName: "eds-dashboard/eds-dashboard.exe"; WorkingDir: "eds-dashboard"; Parameters: " servers_start.php allservers"; ShowCmd: hidden;**

**Comment by Scott-G** [comment] 2023-01-05 11:02
Thanks @webitman - This seems to work for me.👍

**Comment by gtnmns** [comment] 2024-02-09 14:52
The solution of @webitman works like a charm in combination with a shortcut to run-devserver.exe in the shell:startup folder.
Thank you very much!
